config/routes.rb
Rails.application.routes.draw do

  resources :moments

  get  '/feedback', to: "feedbacks#index"

  resources :reports

  resources :reminders

  resources :profiles

  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: "home#index"

end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :user
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  before_action :set_reminder, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  respond_to :html

  def index
    @reminders = Reminder.all
    respond_with(@reminders)
  end

  def show
    respond_with(@reminder)
  end

  def new
    @reminder = Reminder.new
    respond_with(@reminder)
  end

  def edit
  end

  def create
    @reminder = Reminder.new(reminder_params)
    @reminder.save
    respond_with(@reminder)
  end

  def update
    @reminder.update(reminder_params)
    respond_with(@reminder)
  end

  def destroy
    @reminder.destroy
    respond_with(@reminder)
  end

  private
    def set_reminder
      @reminder = Reminder.find(params[:id])
    end

    def reminder_params
      params.require(:reminder).permit(:user_id, :by_phone, :by_email, :time)
    end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_form.html.erb
<%= form_for(@reminder) do |f| %>
  <% if @reminder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reminder.errors.count, "error") %> prohibited this reminder from being saved:</h2>

      <ul>
      <% @reminder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :by_phone %><br>
    <%= f.check_box :by_phone %>
  </div>
  <div class="field">
    <%= f.label :by_email %><br>
    <%= f.check_box :by_email %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reminders/edit.html.erb
<h1>Editing reminder</h1>

<%= render 'form' %>

<%= link_to 'Show', @reminder %> |
<%= link_to 'Back', reminders_path %>

app/views/reminders/index.html.erb
<h1>Listing reminders</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>By phone</th>
      <th>By email</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reminders.each do |reminder| %>
      <tr>
        <td><%= reminder.user_id %></td>
        <td><%= reminder.by_phone %></td>
        <td><%= reminder.by_email %></td>
        <td><%= reminder.time %></td>
        <td><%= link_to 'Show', reminder %></td>
        <td><%= link_to 'Edit', edit_reminder_path(reminder) %></td>
        <td><%= link_to 'Destroy', reminder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reminder', new_reminder_path %>

app/views/reminders/new.html.erb
<h1>New reminder</h1>

<%= render 'form' %>

<%= link_to 'Back', reminders_path %>

app/views/reminders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @reminder.user_id %>
</p>

<p>
  <strong>By phone:</strong>
  <%= @reminder.by_phone %>
</p>

<p>
  <strong>By email:</strong>
  <%= @reminder.by_email %>
</p>

<p>
  <strong>Time:</strong>
  <%= @reminder.time %>
</p>

<%= link_to 'Edit', edit_reminder_path(@reminder) %> |
<%= link_to 'Back', reminders_path %>