config/routes.rb
Rails.application.routes.draw do

  resources :moments

  get  '/feedback', to: "feedbacks#index"

  resources :reports

  resources :reminders

  resources :profiles

  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: "home#index"

end

app/models/moment.rb
class Moment < ActiveRecord::Base
  belongs_to :user

  scope :mine, -> (user) { where("user_id = ?", user.id) }
  # scope :this_week, -> (user) { where("date >= ? AND user_id = ?", Date.current.in_time_zone(user.time_zone).beginning_of_week.to_date, user.id) }
  scope :mine_yesterday, -> (user) { where("date = ? AND user_id = ?", Date.yesterday.in_time_zone(user.time_zone), user.id) }
  scope :mine_today, -> (user) { where("date = ? AND user_id = ?", Date.current.in_time_zone(user.time_zone), user.id) }

  validates_presence_of :how_do_you_feel, :why

  before_update :encrypt


  def encrypt
    cryptor = Cryptor::SymmetricEncryption.new(ENV["SECRET_KEY_CRYPTOR"])
    self.why = cryptor.encrypt(self.why)
    self.what_went_well = cryptor.encrypt(self.what_went_well)
  end

  def self.my_moment_dates(user)
    moment_dates = Array.new
    user.moments.each do |moment|
      moment_dates.push(moment.date)
    end
    return moment_dates.uniq
  end

end

app/controllers/moments_controller.rb
class MomentsController < ApplicationController
  before_action :set_moment, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!, :except => [:create]

  respond_to :html

  def index
    @moments_today = Moment.mine_today(current_user)
    @moments_yesterday = Moment.mine_yesterday(current_user)
    @moments = Moment.mine(current_user)
    # @moment_dates = Moment.my_moment_dates(current_user)



    respond_with(@moments)
  end

  def show
    respond_with(@moment)
  end

  def new
    @moment = Moment.new
    respond_with(@moment)
  end

  def edit
    @moment.why = cryptor.decrypt(@moment.why)
    @moment.what_went_well = cryptor.decrypt(@moment.what_went_well)
  end

  def create
    @moment = Moment.new(moment_params)
    respond_to do |format|
      if user_signed_in?
        @moment.why = cryptor.encrypt(@moment.why)
        @moment.what_went_well = cryptor.encrypt(@moment.what_went_well)
        @moment.date = Date.current.in_time_zone(current_user.time_zone)
          if @moment.save
            format.html { redirect_to @moment, notice: 'Moment was successfully created.' }
            format.json { render :show, status: :created, location: @moment }
          else
            format.html { render :new }
            format.json { render json: @moment.errors, status: :unprocessable_entity }
          end
      else
        cookies[:guest_moment]           = { :value    => "exists",
                                            :expires  => Time.now + 900 }
        cookies[:how_do_you_feel]       = { :value    => moment_params[:how_do_you_feel],
                                            :expires  => Time.now + 900 }
        cookies[:why]                   = { :value    => cryptor.encrypt(moment_params[:why]),
                                            :expires  => Time.now + 900 }
        cookies[:what_went_well]        = { :value    => cryptor.encrypt(moment_params[:what_went_well]),
                                            :expires  => Time.now + 900 }

        format.html { redirect_to new_user_session_path}

      end
    end
  end

  def update
    @moment.update(moment_params)
    respond_with(@moment)
  end

  def destroy
    @moment.destroy
    respond_with(@moment)
  end

  private
    def set_moment
      @moment = Moment.find(params[:id])
    end

    def moment_params
      params.require(:moment).permit(:date, :how_do_you_feel, :why, :what_went_well, :user_id)
    end

end

app/helpers/moments_helper.rb
module MomentsHelper
  def mood_average(date)
    mood = Moment.where('date = ?', date)
    return mood.average(:how_do_you_feel)
  end
end

app/views/moments/_add_moment.html.erb
<div class=" large-5 columns">
  <aside class="ad">
    <header>
      <h1 class="title ad__title">&#x266A; Don't you forget about me &#x266A;</h1>
    </header>
    <div class="center">
      <figure class="feeling feeling--sad">
        <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-sad.png" alt="Feeling sad %>" class="mood__emoticon">
      </figure>
    </div>
    <%= link_to "Add a moment", new_moment_path, class: "button radius ad__button" %>
  </aside>
</div>

app/views/moments/_form.html.erb
<section class="new-moment__form">
  <%= form_for(@moment, html: {class: "moment__form"}) do |f| %>
    <% if @moment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@moment.errors.count, "error") %> prohibited this moment from being saved:</h2>

        <ul>
        <% @moment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :how_do_you_feel, class: "form__question" %>

      <%= f.label :how_do_you_feel, "Happy", :value => "1", class: "option--feeling" do %>
        <%= f.radio_button :how_do_you_feel, 1 %>
        <figure class="feeling feeling--happy">
          <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-happy.png" alt="Feeling Happy" class="option--feeling__emoticon">
          <figcaption class="option--feeling__emotion">Happy</figcaption>
        </figure>
      <% end %>

      <%= f.label :how_do_you_feel, "Pleasant", :value => "2", class: "option--feeling" do %>
        <%= f.radio_button :how_do_you_feel, 2 %>
        <figure class="feeling feeling--pleasant">
          <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-pleasant.png" alt="Feeling Pleasant" class="option--feeling__emoticon">
          <figcaption class="option--feeling__emotion">Pleasant</figcaption>
        </figure>
      <% end %>

      <%= f.label :how_do_you_feel, "Sad", :value => "3", class: "option--feeling" do %>
        <%= f.radio_button :how_do_you_feel, 3 %>
        <figure class="feeling feeling--sad">
          <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-sad.png" alt="Feeling Sad" class="option--feeling__emoticon">
          <figcaption class="option--feeling__emotion">Sad</figcaption>
        </figure>
      <% end %>

      <%= f.label :how_do_you_feel, "Angry", :value => "4", class: "option--feeling" do %>
        <%= f.radio_button :how_do_you_feel, 4 %>
        <figure class="feeling feeling--angry">
          <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-angry.png" alt="Feeling Angry" class="option--feeling__emoticon">
          <figcaption class="option--feeling__emotion">Angry</figcaption>
        </figure>
      <% end %>
    </div>

     <div class="field">
      <%= f.label :why, "Why", class: "form__question" %>
      <%= f.text_area :why, class: "form__field form__field--text-area" %>
    </div>

     <div class="field">
      <%= f.label :what_went_well, "What went well today", class: "form__question" %>
      <%= f.text_area :what_went_well, class: "form__field form__field--text-area" %>
    </div>


    <div class="actions">
        <% if user_signed_in? %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.submit "Note it!", class: "button radius form__button" %>
        <% else %>
          <%= f.submit "Login and Note it!", class: "button radius form__button" %>
        <% end %>
    </div>
  <% end %>
</section>

app/views/moments/edit.html.erb
<section class="screen screen--edit-moment">
  <div class="row">
    <div class="small-12 columns">
      <section class="edit-moment__response">
        <% if @moment.date == Date.current %>
          <header>
            <p class="clearfix">
              <span class="show-moment__date"><%= @moment.date.strftime("%m/%d/%Y") %></span>
              <span class="show-moment__menu right">
                <%= link_to 'Cancel', @moment, class: "button radius tiny show-moment__menu__item" %>
              </span>
            </p>
          </header>
          <section class="edit-moment__questions">
            <%= render 'form' %>
          </section>
        <% end %>
      </section>
    </div>
  </div>
</section>

app/views/moments/index.html.erb
<section class="screen screen--index-moment">
  <div class="row">
    <div class="large-12 columns">

      <!-- TODAY -->
      <% unless @moments_today.blank? %>
        <h2 class="list__title">Today</h2>
        <ul class="list list--moments">
          <li class="list__item">
            <section class="tile tile--daily-moments">
              <div class="row">
                <div class="small-3 large-3 columns">
                  <figure class="feeling feeling--<%= mood(mood_average(Date.current.in_time_zone(@current_user.time_zone))) %>">
                    <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-<%= mood(mood_average(Date.current.in_time_zone(@current_user.time_zone))) %>.png" alt="Feeling <%= mood(mood_average(Date.current.in_time_zone(@current_user.time_zone))) %>" class="mood__emoticon">
                    <figcaption class="mood">
                      <%= mood(mood_average(Date.current.in_time_zone(@current_user.time_zone))) %>
                    </figcaption>
                  </figure>
                </div>

                <div class="small-7 large-6 columns">
                  <div class="row">
                    <div class="large-6 columns">
                      <p class="daily-moments__count">Moments: 3</p>
                    </div>
                    <div class="large-6 columns">
                      <p class="daily-moments__count">Good things: 2</p>
                    </div>
                  </div>
                </div>
                <div class="small-2 large-3 columns">
                  <p class="daily-moments__menu">i c o n </p>
                </div>
              </div>

              <div class="row hide">
                <div class="small-12 columns">
                  <% @moments_today.each do |moment| %>
                    <p>*Feeling with mood*<br><%= truncate(cryptor.decrypt(moment.why), length: 35) %></p>
                    <p>*List of Good things*<br><%= truncate(cryptor.decrypt(moment.what_went_well), length: 35) %></p>
                  <% end %>
                </div>
              </div>
            </section>

          </li>
        </ul>
      <% else %>
        <%= render 'add_moment' %>
      <% end %>

    </div>
  </div>
</section>


<!-- PLAY TIME -->
<!-- <%# if @moments %>

  <%# @moment_dates.each do |date| %>
    <section class="moment-day">
      <header class="moment-day__header">
        <h1 class="moment-day__date"><%#= date.strftime("%m/%d/%Y") %></h1>
      </header>
      <h2>*Average Mood for today*</h2>
      <p><%#= mood_average(date) %></p>

      <%# @moments.each do |moment| %>
        <%# if moment.date == date %>
          <div class="">
            <p>*Feeling with mood*<br><%#= truncate(cryptor.decrypt(moment.why), length: 35) %></p>
            <p>*List of Good things*<br><%#= truncate(cryptor.decrypt(moment.what_went_well), length: 35) %></p>
          </div>
        <%# end %>
      <%# end %>
    </section>
  <%# end %>

<%# else %>
  <%#= render 'add_moment' %>
<%# end %> -->




<!-- OLD CODE -->
<!--     <%# if @todays_moment %>
      <div class=" large-6 columns">
        <section class="index-moment index-moment--today">
          <header>
            <h1 class="title index-moment__title">Today</h1>
          </header>
          <p class="index-moment__excerpt"><%#= truncate(cryptor.decrypt(@todays_moment.what_went_well), length: 35) %></p>
          <div class="index-moment__mood-shift">
            <figure class="feeling feeling--<%#= mood(@todays_moment.how_do_you_feel) %>">
              <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-<%#= mood(@todays_moment.how_do_you_feel) %>.png" alt="Feeling <%#= mood(@todays_moment.how_do_you_feel) %>" class="mood__emoticon">
              <figcaption class="mood"><%#= mood(@todays_moment.how_do_you_feel) %></figcaption>
            </figure>
            <span class="index-moment__mood-shift__arrow--right">&#10157;</span>
            <figure class="feeling feeling--<%#= mood(@todays_moment.how_do_you_feel_now) %>">
              <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-<%#= mood(@todays_moment.how_do_you_feel_now) %>.png" alt="Feeling <%#= mood(@todays_moment.how_do_you_feel_now) %>" class="mood__emoticon">
              <figcaption class="mood"><%#= mood(@todays_moment.how_do_you_feel_now) %></figcaption>
            </figure>
          </div>
          <%#= link_to "View Notetato", @todays_moment, class: "button radius index-moment__button" %>
        </section>
      </div>
    <%# else %>
      <%#= render 'add_moment' %>
    <%# end %> -->

app/views/moments/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <section class="screen screen--new-moment">
    <header>
      <h1 class="title screen__title">Add a Notetato</h1>
    </header>
          <%= render 'form' %>
    </section>
  </div>
</div>

app/views/moments/show.html.erb
<section class="screen screen--show-moment">
  <div class="row">
    <div class="large-12 columns">

      <section class="show-moment__response">
        <header>
          <p class="clearfix">
            <span class="show-moment__date"><%= @moment.date.strftime("%m/%d/%Y") %></span>
            <% if @moment.date == Date.current %>
              <span class="show-moment__menu right">
              <%= link_to 'Edit', edit_moment_path(@moment), class: "button radius tiny show-moment__menu__item" %>
              </span>
            <% end %>
          </p>
        </header>

        <section class="show-moment__questions">
          <p class="show-moment__question">How do you feel?</p>
          <figure class="feeling feeling--<%= mood(@moment.how_do_you_feel) %>">
            <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/emoticons/notetato-<%= mood(@moment.how_do_you_feel) %>.png" alt="Feeling <%= mood(@moment.how_do_you_feel) %>" class="option--feeling__emoticon">
            <figcaption class="option--feeling__emotion">
              <%= mood(@moment.how_do_you_feel) %>
            </figcaption>
          </figure>

          <p class="show-moment__question">Why?</p>
          <% if !@moment.why.blank? %>
            <%= simple_format(cryptor.decrypt(@moment.why), class: "show-moment__answer") %>
          <% else %>
            <p class="show-moment__answer show-moment__answer--none">No answer.</p>
          <% end %>

          <p class="show-moment__question">Tell me about one good thing that happened today</p>
          <% if !@moment.what_went_well.blank? %>
            <%= simple_format(cryptor.decrypt(@moment.what_went_well), class: "show-moment__answer") %>
          <% else %>
            <p class="show-moment__answer show-moment__answer--none">No answer.</p>
          <% end %>


        </section>
        <footer>
          <div class="clearfix">
            <%= link_to 'Delete', @moment, method: :delete, data: { confirm: 'Are you sure?' }, class: "button radius show-moment__button--delete" %>
          </div>
        </footer>
      </section>
    </div>
  </div>
</section>