config/routes.rb
Rails.application.routes.draw do

  resources :moments

  get  '/feedback', to: "feedbacks#index"

  resources :reports

  resources :reminders

  resources :profiles

  devise_for :users, :controllers => { registrations: 'registrations' }

  root to: "home#index"

end

app/views/layouts/_feedback.html.erb
<% if user_signed_in? && params[:controller] != 'feedbacks' %>
  <div class="feedback__button">
    <%= link_to "feedback!", feedback_path, class: "button button--feedback" %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header class="container__bar">
  <h1 class="title">Notetato</h1>
  <img src="https://s3-us-west-2.amazonaws.com/notetato-static-media/notetato-logo-grey.png" class="app-logo">
  <%= render 'layouts/login_state' %>
  <% if current_page?(root_path) && !user_signed_in? %>
    <p class="value-statement">Note <span class="lowercase">and</span> improve your mood <span class="lowercase">with</span> Notetato.</p>
  <% elsif user_signed_in? %>
    <%= render 'layouts/navigation' %>
  <% end %>
</header>

app/views/layouts/_login_state.html.erb
<% if user_signed_in? %>
  <div class="login-state">
    <p>
      <%= link_to 'Sign-out', destroy_user_session_path, :method => :delete, class: "login-state__message login-state__message--sign-out" %>
    </p>
  </div>
<% else %>
  <div class="login-state">
    <p><%= link_to 'Log-in', new_user_session_path, class: "login-state__message login-state__message--login" %> <em>or</em> <%= link_to 'Register', new_user_registration_path, class: "login-state__message login-state__message--sign-up" %></p>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="message <%= flash_class(type) %> fade-out">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navigation">
  <ul class="navigation__items">
    <li class="navigation__item <%= 'navigation__item--active' if params[:controller] == 'reports' %>">
      <%= link_to "Report", reports_path, class: "navigation__item__link #{'navigation__item__link--active' if params[:controller] == 'reports'}"%>
    </li>
    <li class="navigation__item <%= 'navigation__item--active' if params[:controller] == 'moments' %>">
      <%= link_to "Moments", moments_path, class: "navigation__item__link #{'navigation__item__link--active' if params[:controller] == 'moments'}"%>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Notetato: Learn from Today, and Focus on Tomorrow" %></title>
    <%= google_webfonts_init({google: ['Lobster', 'Varela Round']}) %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <section class="container">
      <div class="row">
        <div class="small-12 columns">
          <div class="row">
            <div class="large-12 columns">
                <%= render 'layouts/header' %>
            </div>
          </div>
          <div class="row">
            <div class="small-12 columns ">
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </section>
    <%= render 'layouts/feedback' %>
  </body>
</html>